spring:
  application:
    name: jamesyxu-second-code
#  ai:
#    openai:
#      api-key: sk-94027d471dfe42a1ad0449a1a5fe7f3e
#      base-url: https://api.deepseek.com
#      chat:
#        options:
#          model: deepseek-chat
#          temperature: 0.7

chat:
  api-key: sk-4d565a8750e94b9abf0f525ed530ddad
  chat-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

server:
  port: 8080